### ISSUE TITLE
Todoist service makes you login after restart

### ISSUE THREAD

**Issue by nchourrout** [avatarkava/recipe-todoist#3]
The Todoist tab prompts to log in after restarting Franz.
This was also mentioned [here](https://github.com/meetfranz/franz/issues/53).

I use Google Auth and Franz 5.0.0 beta 14

**Comment by fagiani** [comment]
@avatarkava any clues on how to fix this? Looks like Franz somehow reloads windows several times during the day and every time it asks to log in to Todoist again. That won't happen with the other services. I really appreciate your initiative and efforts on this recipe and also your help with this issue.

**Comment by avatarkava** [comment]
@fagiani not sure, haven't had much chance to look at it as I did the minimum amount of work possible to get the original recipe from Franz 4 working with v5.  I'll try to take a look into it, as it's been annoying me as well :)

**Comment by avatarkava** [comment]
@adlk I don't have a ton of expertise with the session handling within Franz - anything in terms of documentation or gotchas I should look at?

**Comment by OskarCarl** [comment]
I'm not exactly sure if this is the best way, but changing the service URL in `package.json` to `"serviceURL": "https://todoist.com/"` works for me. It seems Franz is handling sessions fine on its own.

**Comment by avatarkava** [comment]
@Kalagon good catch - at some point I guess todoist changed their login scheme and canonical url which is likely why the sessions are being wonky - it's probably forcing a refresh of the session when navigating direct to the login URL.  Making that update now, keep an eye on the update once it gets pulled back into the central plugins repo.

**Comment by fagiani** [comment]
@avatarkava thanks for that update. Can I ask how can I update to get that working? I was expecting to be on the last Franz update a couple of days ago but it didn't happen.

Tks a lot!

**Comment by avatarkava** [comment]
Hey @fagiani, right now it looks like Franz is holding back any updates to plugins until they get the 'category' feature in.  I'm not sure what the timeline on that release is, but you can follow the actual deployment ticket on their end here: https://github.com/meetfranz/plugins/issues/116

If you want to manually make the change in your install while you're waiting for that, you can change the files in the plugin.  In Windows for example, it would be in `%AppData%/Roaming/Franz/recipes/todoist/package.json`.  Update to match what is here: https://github.com/avatarkava/recipe-todoist/blob/master/package.json

**Comment by fagiani** [comment]
@avatarkava after some digging, I was able to find it and it works great!

For the record, on a `MacOS` it is located on `~/Library/Application Support/Franz/recipes/todoist/package.json`

Keep Rocking!

**Comment by riddla** [comment]
Thx @avatarkava and @fagiani, works for me, too :)

For the lazy:

`sed -i -- 's/Users\/showLogin//g' ~/Library/Application\ Support/Franz/recipes/todoist/package.json`

... directly removes the `Users/showLogin/` part within `package.json`.
