### ISSUE TITLE
Todoist keeps logging me out

### ISSUE THREAD

**Issue by phillipprado** [avatarkava/recipe-todoist#5]
macOS 10.13.3
franz 5.0.0 beta 17

Issue: Every time Todoist refreshes it logs me out. 

Recreate: This can be recreated by either closing and reopening the Franz client, or simply by manually refreshing the plugin itself by clicking cmd-r (in the case of macOS) while Todoist has focus.

**Comment by avatarkava** [comment]
Hey Phillip - fixed it here a bit ago but waiting for Franz to release the update - more info (and a temp workaround) are in this ticket: https://github.com/avatarkava/recipe-todoist/issues/3

**Comment by phillipprado** [comment]
Thank you!
